### PR TITLE
In our project we wanted to display images in the feature files.

### PR DESCRIPTION
**Pull request by bheerschop**

### CODE REVIEW

**Comment by bheerschop** [comment]
Resolved the conflict on packages.config

**Comment by marktaling** [comment]
As we understand it, this feature's purpose is to improve the way images are shown, when already present in the markdown.
Could you provide some screenshots of how this will look, both in the feature and when clicked on (the fancybox)? This will help us to determine the impact for our existing userbase.

**Comment by bheerschop** [comment]
1_addlinktofeaturefile
2_displaysmallimage
3_displaybigimage

**Note**: In the mean time the jquery version used in Augurk has been updated to version 3.1.1 but this version does not work with the used fancybox version.

**Comment by jmezach** [comment]
As noted by @marktaling we couldn't get this to work properly with jQuery 3.1.1. If you can get it to work with that, please let us know, until then we'll close this PR.

**Pull request closed without merging**
