### PR TITLE
Minor mistake in Dutch

### PR DESCRIPTION
**Pull request by ptoonen**
;-)

### CODE REVIEW

**Comment by jmezach** [comment]
;) Perhaps we should fix the link itself, rather than fixing the dutch words.

**Comment by jmezach** [comment]
@marktaling Do we want to release this as 2.8.2?

**Comment by marktaling** [comment]
Might as well. Even though we have Some practical roadbumps for 3.0, I don’t intend to release a 2.9.0
As such, there is no point in saving up the minor fixes. Let’s just release whatever we fix until we get our 3.0 release flow on the road.

**Comment by jmezach** [comment]
Released this as [2.8.2](https://github.com/Augurk/Augurk/releases/tag/2.8.2). Thanks @ptoonen for your contribution.

**Pull request merged**
