### PR TITLE
Minor Updates / Fixes

### PR DESCRIPTION
**Pull request by marktaling**
+ Updated Packages
+ Fixed remaining reference to branches to now refer to product
+ Disabled removal of server tags from scenarios

### CODE REVIEW

**Comment by jmezach** [comment]
Having all these JavaScript and CSS files in our repository makes it a bit hard to see what really changed. Perhaps we should look into managing those with npm. Not blocking for this PR as far as I'm concerned, but maybe create an issue for it.

**Comment by marktaling** [comment]
Agreed. We really should separate these scripts from our own.

**Comment by jmezach** [comment]
Is there anything holding this back?

**Comment by marktaling** [comment]
No, not really. I suppose there isn't a real approve button on GitHub. I'll try to push it this week.

**Comment by jmezach** [comment]
;) There is a Merge Pull request button, but no real approval before you can merge it. I think you can set up verification steps so you can do some automated things (ie. build) before merging it in.

**Pull request merged**
